services:
  docs:
    image: openbis_upload_helper_local_docs
    container_name: openbis_upload_helper_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./openbis_upload_helper:/app/openbis_upload_helper:z
    ports:
      - '9000:9000'
    command: /start-docs
